### ISSUE TITLE
preview is broken b/c api change

### ISSUE THREAD

**Issue by SuperStormer** [jmir1/osu-preview#2]
Attempting to preview any beatmap (eg. https://jmir.xyz/osu/preview.html#845391) fails. 

Console Errors:
![image](https://user-images.githubusercontent.com/41648788/162347582-65bcfd77-5d32-4ac9-b687-ed06240e973a.png)

Cause:
This is because the API response (https://api.chimu.moe/v1/map/845391 for instance) no longer includes a data key.

Fix (untested):
Change every instance of `data.data` in https://github.com/jmir1/osu-preview/blob/master/src/preview.html to just `data`.

I can make a PR if needed.

**Comment by SuperStormer** [comment]
I believe a CORS error is also thrown, so `fetch("https://api.chimu.moe/v1/download/" + setID + "?n")` should be `fetch("https://chimu.moe/d/" + setID)` (or use the `DownloadPath` key from the initial API response).

**Comment by jmir1** [comment]
i found the same things as you but i havent updated yet because chimu.moe still downloads the wrong maps sometimes.
